{% set name = "sphinxext-rediraffe" %}
{% set version = "0.2.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc8bbe6b3334a3bfc8ed0d1d6b2e831de9c06f123fa7d635cfb8192141ca4140
  
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - sphinx >=2.0

test:
  imports:
    - sphinxext.rediraffe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wpilibsuite/sphinxext-rediraffe
  summary: Sphinx Extension that redirects non-existent pages to working pages.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - bollwyvl
